# Generated by Django 5.2.12 on 2026-03-16 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('genre', models.CharField(db_index=True, max_length=100, verbose_name='genre')),
                ('duration_minutes', models.PositiveSmallIntegerField(verbose_name='duration (min)')),
                ('release_date', models.DateField(db_index=True, verbose_name='release date')),
                ('synopsis', models.TextField(blank=True, verbose_name='synopsis')),
                ('poster_url', models.URLField(blank=True, verbose_name='poster URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(db_index=True, max_length=50, verbose_name='room')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts at')),
                ('ends_at', models.DateTimeField(verbose_name='ends at')),
                ('total_seats', models.PositiveSmallIntegerField(verbose_name='total seats')),
                ('available_seats', models.PositiveSmallIntegerField(verbose_name='available seats')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price (BRL)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.movie')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=5, verbose_name='row')),
                ('number', models.PositiveSmallIntegerField(verbose_name='number')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('purchased', 'Purchased')], db_index=True, default='available', max_length=10, verbose_name='status')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.session')),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
                'ordering': ['row', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('purchased', 'Purchased'), ('expired', 'Expired')], db_index=True, default='locked', max_length=10, verbose_name='status')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='locked until')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='purchased at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.seat')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['movie', 'starts_at'], name='session_movie_starts_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['session', 'status'], name='seat_session_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('session', 'row', 'number')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user', 'status'], name='ticket_user_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('session', 'seat')},
        ),
    ]
